version: '3.7'
services:
  web:
    build: .
    ports:
      - 5000:8000
    restart: always
    environment:
      SECRET_KEY: -l#[^89:Bjn^V7V7HGv*
      MONGODB: "mongodb://root:rootpassword@mongodb:27017"
      MONGODB_DATABSE: db
      MONGODB_DATABSE_COLLECTION: events
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:6.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend


volumes:
  mongodb_data_container:

networks:
  backend:
    driver: bridge
